name: Example Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        echo "Running tests..."
    - name: Print commit information
      run: |
        echo "Commit message: ${{ github.event.head_commit.message }}"
        echo "Commit author: ${{ github.event.head_commit.author.name }}"
        echo "Commit SHA: ${{ github.event.head_commit.id }}"
    - name: Check updated codes
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.event.after }}


